/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'memberId' : string,
  'senderIsProvider' : boolean,
  'slotKey' : string,
  'content' : string,
  'serviceProviderId' : string,
  'timestamp' : Time,
}
export interface Quote {
  'id' : bigint,
  'title' : string,
  'slotKey' : string,
  'serviceProviderId' : string,
  'businessName' : string,
  'description' : string,
  'timestamp' : Time,
  'providerName' : string,
  'price' : string,
}
export interface Registration {
  'id' : bigint,
  'userId' : string,
  'name' : string,
  'timestamp' : Time,
  'category' : string,
  'phone' : string,
  'requirements' : string,
  'location' : string,
  'product' : string,
}
export interface ServiceProviderProfile {
  'name' : string,
  'businessName' : string,
  'category' : string,
  'phone' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export interface PublicRegistration { 'product' : string, 'location' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllRegistrations' : ActorMethod<[], Array<Registration>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getChatMessages' : ActorMethod<[string, string, string], Array<ChatMessage>>,
  'getMyRegistrations' : ActorMethod<[], Array<Registration>>,
  'getMyServiceProviderProfile' : ActorMethod<
    [],
    [] | [ServiceProviderProfile]
  >,
  'getProductCount' : ActorMethod<[string, string], bigint>,
  'getProductsForCategory' : ActorMethod<[string], Array<string>>,
  'getProviderChatMessages' : ActorMethod<
    [string, string, string],
    Array<ChatMessage>
  >,
  'getQuotesForSlot' : ActorMethod<[string, string], Array<Quote>>,
  'getSlotMembers' : ActorMethod<[string, string], Array<Registration>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasSpPaidForSlot' : ActorMethod<[string, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordSpSlotPayment' : ActorMethod<[string, string], undefined>,
  'registerForProduct' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'registerServiceProvider' : ActorMethod<[ServiceProviderProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendChatMessage' : ActorMethod<
    [string, string, string, string, boolean],
    undefined
  >,
  'sendChatMessageAsProvider' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitQuote' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'getPublicRegistrationsForCategory' : ActorMethod<[string], Array<PublicRegistration>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];