/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'phone' : IDL.Text,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
  'product' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'memberId' : IDL.Text,
  'senderIsProvider' : IDL.Bool,
  'slotKey' : IDL.Text,
  'content' : IDL.Text,
  'serviceProviderId' : IDL.Text,
  'timestamp' : Time,
});
export const ServiceProviderProfile = IDL.Record({
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});
export const Quote = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'slotKey' : IDL.Text,
  'serviceProviderId' : IDL.Text,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'providerName' : IDL.Text,
  'price' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getChatMessages' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getMyRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getMyServiceProviderProfile' : IDL.Func(
      [],
      [IDL.Opt(ServiceProviderProfile)],
      ['query'],
    ),
  'getProductCount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
  'getProductsForCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getProviderChatMessages' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getQuotesForSlot' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Quote)],
      ['query'],
    ),
  'getSlotMembers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasSpPaidForSlot' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordSpSlotPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerForProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerServiceProvider' : IDL.Func([ServiceProviderProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendChatMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'sendChatMessageAsProvider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitQuote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'phone' : IDL.Text,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
    'product' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'memberId' : IDL.Text,
    'senderIsProvider' : IDL.Bool,
    'slotKey' : IDL.Text,
    'content' : IDL.Text,
    'serviceProviderId' : IDL.Text,
    'timestamp' : Time,
  });
  const ServiceProviderProfile = IDL.Record({
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Quote = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'slotKey' : IDL.Text,
    'serviceProviderId' : IDL.Text,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'providerName' : IDL.Text,
    'price' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getChatMessages' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getMyRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getMyServiceProviderProfile' : IDL.Func(
        [],
        [IDL.Opt(ServiceProviderProfile)],
        ['query'],
      ),
    'getProductCount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
    'getProductsForCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getProviderChatMessages' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getQuotesForSlot' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Quote)],
        ['query'],
      ),
    'getSlotMembers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasSpPaidForSlot' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordSpSlotPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerForProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerServiceProvider' : IDL.Func([ServiceProviderProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendChatMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'sendChatMessageAsProvider' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitQuote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };